# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a924aac2502326d4cbeecc5f783916e965f31bdf31b864ccc7a0a234c297735810cab5a432b2cbe99520cd9ad6d00947e220f41749220e2d2f24e5529d855421

test:
  secret_key_base: 98690d473e319468b001e9d9a2b65685407981c3acd7309cc0670e292bf3ed156979d1b28b63f94d928987ccbf14857237b47a681c116d6170d09b0b3ac235b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
